/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Mutation: {};
  Query: {};
  Todo: { // root type
    checked: boolean; // Boolean!
    description: string; // String!
    id: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    clearCompleted: NexusGenRootTypes['Todo']; // Todo!
    delete: NexusGenRootTypes['Todo']; // Todo!
    post: NexusGenRootTypes['Todo']; // Todo!
    update: NexusGenRootTypes['Todo']; // Todo!
    updateChecked: NexusGenRootTypes['Todo']; // Todo!
    updateDescription: NexusGenRootTypes['Todo']; // Todo!
  }
  Query: { // field return type
    get: NexusGenRootTypes['Todo'][]; // [Todo!]!
    getOnlyActive: NexusGenRootTypes['Todo'][]; // [Todo!]!
    getOnlyCompleted: NexusGenRootTypes['Todo'][]; // [Todo!]!
    getSingle: NexusGenRootTypes['Todo'] | null; // Todo
  }
  Todo: { // field return type
    checked: boolean; // Boolean!
    description: string; // String!
    id: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    clearCompleted: 'Todo'
    delete: 'Todo'
    post: 'Todo'
    update: 'Todo'
    updateChecked: 'Todo'
    updateDescription: 'Todo'
  }
  Query: { // field return type name
    get: 'Todo'
    getOnlyActive: 'Todo'
    getOnlyCompleted: 'Todo'
    getSingle: 'Todo'
  }
  Todo: { // field return type name
    checked: 'Boolean'
    description: 'String'
    id: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    delete: { // args
      id: number; // Int!
    }
    post: { // args
      description: string; // String!
    }
    update: { // args
      checked: boolean; // Boolean!
      description: string; // String!
      id: number; // Int!
    }
    updateChecked: { // args
      checked: boolean; // Boolean!
      id: number; // Int!
    }
    updateDescription: { // args
      description: string; // String!
      id: number; // Int!
    }
  }
  Query: {
    getSingle: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}